name: Generate Red Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Her 6 saatte bir otomatik 癟al覺覺r
  workflow_dispatch: # Manuel 癟al覺t覺rma se癟enei

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clean old snake files
        run: |
          rm -rf dist
          mkdir -p dist
          echo "完 Old SVG files removed."

      - name: Generate Red Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Nicat-Mammadov
          outputs: |
            dist/github-contribution-grid-snake-red.svg?palette=rose-pine
            dist/github-contribution-grid-snake-red-dark.svg?palette=rose-pine

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
